<a href="https://colab.research.google.com/github/Jeevita-R/da_notes/blob/main/tclass1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

kewjdhgwhfjekd


In [ ]:
s='good evening'
print(len(s))

12


ksdjhgfcdfwiefhowiefhweufwkehfkwehf


In [ ]:
l=[10,20,30,40]
print(l*2)

[10, 20, 30, 40, 10, 20, 30, 40]


In [ ]:
import numpy as np

In [ ]:
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [ ]:
np.array([12,3.4,5.6,9])

array([12. ,  3.4,  5.6,  9. ])

In [ ]:
np.array([10,20,30,40,'hai'])

array(['10', '20', '30', '40', 'hai'], dtype='<U21')

In [ ]:
np.array([10,20,30,40,{1,2}])


array([10, 20, 30, 40, {1, 2}], dtype=object)

In [ ]:
a=np.array([12,3,67,89,True])
print(a.dtype)

int64


In [ ]:
a=np.array([1,2,{3,4}])
print(a.dtype)
print(type(a[0]))

object
<class 'int'>


In [ ]:
np.array([1,2,3,4,[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [ ]:
a=np.array([1,2,3,4,5,6])
a.max()

6