<a href="https://colab.research.google.com/github/Jeevita-R/da_notes/blob/main/tc2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([12,34,56,{1,78},90])
a.ndim

1

In [ ]:
b=np.array([[1,2,3],[8.6,9,7],[4,5,6]])
b.ndim

2

In [ ]:
c=np.array([[[[1,2,3,4,5,6,7]]]])
c.ndim

4

In [ ]:
arr1=np.array([10,23,45,67,89])
len(arr1)

5

In [ ]:
arr2=np.array([[12,34,56,78],[98,76,54,32]])
arr2.shape

(2, 4)

In [ ]:
arr1.shape

(5,)

In [ ]:
arr3=np.array([[[12,34,56],[4,5,6]],[[5,7,8],[2,3,4]]])
arr3.shape

(2, 2, 3)

In [ ]:
arr1.size

5

In [ ]:
arr2.size

8

In [ ]:
arr3.size

12

In [ ]:
arr=np.array([[1,2],[3,4],[6,7],[8,9],[6,7],[7,9]])
arr.shape

(6, 2)

In [ ]:
arr.reshape(2,6)

array([[1, 2, 3, 4, 6, 7],
       [8, 9, 6, 7, 7, 9]])

In [ ]:
list(range(1,6))

[1, 2, 3, 4, 5]

In [ ]:
np.arange(1,6.2,1.2)

array([], dtype=complex128)

In [ ]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr.reshape(-1)

array([1, 2, 3, 4, 6, 7, 8, 9, 6, 7, 7, 9])

In [ ]:
arr3.reshape(-1)#flattening an array

array([12, 34, 56,  4,  5,  6,  5,  7,  8,  2,  3,  4])

In [ ]:
import random
random.randint(2,3)

2

In [ ]:
np.random.randint(1000,9999,10)

array([2247, 1889, 1466, 4331, 3557, 4692, 1305, 9116, 8154, 5839])

In [ ]:
np.random.randint(2,6)

3