<a href="https://colab.research.google.com/github/Jeevita-R/da_notes/blob/main/tc3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.random.rand(10)

array([0.73531436, 0.86473246, 0.67356159, 0.5516945 , 0.85776835,
       0.34120341, 0.02632537, 0.39984133, 0.60273299, 0.6367311 ])

In [ ]:
np.random.randn(100)

In [ ]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [ ]:
np.ones((6,2))

In [ ]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.identity(20)

In [ ]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [ ]:
arr2=arr1.copy()
arr2

array([10, 20, 30, 40, 50])

In [ ]:
arr1[3]=400
arr1

array([ 10,  20,  30, 400,  50])

In [ ]:
arr2

array([10, 20, 30, 40, 50])

In [ ]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [ ]:
arr=np.array([12,34,56,78,90])
arr[1:]

array([34, 56, 78, 90])

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,4,3,2,5],[5,6,4,3,2]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  4,  3,  2,  5],
       [ 5,  6,  4,  3,  2]])

In [ ]:
arr[::2,:4]

array([[1, 2, 3, 4],
       [1, 4, 3, 2]])