<a href="https://colab.research.google.com/github/Jeevita-R/da_notes/blob/main/tc4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,23,4,5,-6,3,-2])
arr2=np.array([2,4,5,7,2,-6,8])

In [ ]:
arr1+arr2

array([ 3, 27,  9, 12, -4, -3,  6])

In [ ]:
arr1-arr2

array([ -1,  19,  -1,  -2,  -8,   9, -10])

In [ ]:
arr1*arr2

array([  2,  92,  20,  35, -12, -18, -16])

In [ ]:
arr1/arr2

array([ 0.5       ,  5.75      ,  0.8       ,  0.71428571, -3.        ,
       -0.5       , -0.25      ])

In [ ]:
arr1//arr2

array([ 0,  5,  0,  0, -3, -1, -1])

In [ ]:
a=np.array([1,2,3])
b=np.array([2,3,2])
a**b

array([1, 8, 9])

In [ ]:
a & b

array([0, 2, 2])

In [ ]:
arr1=np.array([12,34,1,2,-3,4])


In [ ]:
arr1+10

array([22, 44, 11, 12,  7, 14])

In [ ]:
arr1-2

array([10, 32, -1,  0, -5,  2])

In [ ]:
2-arr1

array([-10, -32,   1,   0,   5,  -2])

In [ ]:
arr1*3

array([ 36, 102,   3,   6,  -9,  12])

In [ ]:
arr1/2

array([ 6. , 17. ,  0.5,  1. , -1.5,  2. ])

In [ ]:
arr1

array([12, 34,  1,  2, -3,  4])

In [ ]:
arr1.max()

34

In [ ]:
arr1.min()

-3

In [ ]:
arr1.mean()

8.333333333333334

In [ ]:
arr=np.array([1,-2,4,-8,6,-5,-3])


In [ ]:
res=abs(arr)

array([1, 2, 4, 8, 6, 5, 3])

In [ ]:
arr

array([ 1, -2,  4, -8,  6, -5, -3])

In [ ]:
arr[1]=20
arr

array([ 1, 20,  4, -8,  6, -5, -3])

In [ ]:
a=np.array(['a'])
b=np.array(['b'])
a+b

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [ ]:
import pandas as pd

In [ ]:
a=pd.Series([10,20,30,40,50])
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
b=pd.Series([12+3j,3.4,6,8.7,9,'pandas'])
b

0    (12+3j)
1        3.4
2          6
3        8.7
4          9
5     pandas
dtype: object

In [ ]:
d={'sname':['A','B','C','D','E'],
   'sid':[1,2,3,4,5],
   'marks':[67,89,98,67,56]}
df=pd.DataFrame(d)
df

sname  sid  marks
0     A    1     67
1     B    2     89
2     C    3     98
3     D    4     67
4     E    5     56

In [ ]:
df['sname'][0]

'A'

In [ ]:
df['sname'][0]='Amar'
df

<ipython-input-49-63b44301cf41>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sname'][0]='Amar'


sname  sid  marks
0  Amar    1     67
1     B    2     89
2     C    3     98
3     D    4     67
4     E    5     56

In [ ]:
df['bg']=['o+ve','o-ve','AB+','o+ve','AB-']
df

sname  sid  marks    bg
0  Amar    1     67  o+ve
1     B    2     89  o-ve
2     C    3     98   AB+
3     D    4     67  o+ve
4     E    5     56   AB-

In [ ]:
df

sname  sid  marks    bg
0  Amar    1     67  o+ve
1     B    2     89  o-ve
2     C    3     98   AB+
3     D    4     67  o+ve
4     E    5     56   AB-

In [ ]:
df['sname'][1:4]

1    B
2    C
3    D
Name: sname, dtype: object